services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ac2264587
      - POSTGRES_DB=testDB
    ports:
      - 6000:5432
