export default {
  singleQuote: true,
  semi: true,
  useTabs: false,
  tabWidth: 2,
  trailingComma: 'all',
  printWidth: 130,
  arrowParens: 'avoid',
  bracketSpacing: true,
  endOfLine: 'auto',

  plugins: ['@trivago/prettier-plugin-sort-imports'],
  importOrder: [
    '^@configs/(.*)$',
    '^@controllers/(.*)$',
    '^@models/(.*)$',
    '^@services/(.*)$',
    '^@utils/(.*)$',
    '^@/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderCaseInsensitive: false,
};
