name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/2-Docthru-team1-BE
            git fetch origin main
            git reset --hard origin/main

            # 환경 변수 파일 로드
            source /etc/profile.d/HanCook-env.sh

            npm install
            export DATABASE_URL="$DATABASE_URL"
            # npx prisma migrate deploy
            npx prisma migrate reset --force
            # npx prisma db seed
            npx tsc

            # 기존 프로세스가 있으면 재시작, 없으면 새로 시작
            authbind --deep pm2 describe "HanCook" > /dev/null
            if [ $? -eq 0 ]; then
              authbind --deep pm2 reload "HanCook" --update-env
            else
              authbind --deep pm2 start dist/src/app.js --name "HanCook" --update-env
            fi

            pm2 status
